"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
# "preserve_hierarchy": true

"files": [
  {
    "source": "/locale/en/Krastorio2.cfg",
    "translation": "/locale/%two_letters_code%/Krastorio2.cfg"
  },
  {
    "source": "/locale/en/Krastorio2Compatibility.cfg",
    "translation": "/locale/%two_letters_code%/Krastorio2Compatibility.cfg"
  },
  {
    "source": "/locale/en/Krastorio2Tips.cfg",
    "translation": "/locale/%two_letters_code%/Krastorio2Tips.cfg"
  },
  {
    "source": "/locale/en/Krastorio2Wiki.cfg",
    "translation": "/locale/%two_letters_code%/Krastorio2Wiki.cfg"
  }
]
