"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy": true

"files": [
  {
    "source": "locale/en/Krastorio2.cfg",
    "dest": "Krastorio2.cfg",
    "translation": "locale/%locale%/Krastorio2.cfg"
  },
  {
    "source": "locale/en/Krastorio2Compatibility.cfg.cfg",
    "dest": "Krastorio2Compatibility.cfg",
    "translation": "locale/%locale%/Krastorio2Compatibility.cfg"
  },
  {
    "source": "locale/en/Krastorio2Tips.cfg.cfg",
    "dest": "Krastorio2Tips.cfg",
    "translation": "locale/%locale%/Krastorio2Tips.cfg"
  },
  {
    "source": "locale/en/Krastorio2Wiki.cfg.cfg",
    "dest": "Krastorio2Wiki.cfg",
    "translation": "locale/%locale%/Krastorio2Wiki.cfg"
  },
]
