name: Feature request
description: Request a new feature to be added to the mod.
labels: ["enhancement"]
assignees:
  - raiguard
body:
  - type: markdown
    attributes:
      value: "
        Please make sure to [search issues](https://github.com/raiguard/krastorio-2/issues?q=is%3Aissue) before creating a new one, to avoid duplicates and centralize conversations. If you wish to ask a question or provide general feedback, please use the [discussions](https://github.com/raiguard/krastorio-2/discussions) tab.

        If your feature request involves another mod, please attach a save file containing the mods in question so I can sync with it.
      "
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Is your feature request related to a problem? If so, please provide a clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you would like to see.
      placeholder: "Biomethanol should be used in..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots related to the feature request here.
